### PR TITLE
Example of running commands with LimitSwitches

### PR DESCRIPTION
**Pull request by duane701**
The use of Trigger in RobotContainer shows how 
to call a function each time the limit switch changes.

DO NOT MERGE!

### CODE REVIEW

**Review by NWSchallock — APPROVED** [review]
I like it! it is simpler than i thought it would be. it makes me happy

**Review by KenyonSchep — APPROVED** [review]
Looks nice and easy!

**Review by jasonplatte — APPROVED** [review]
LGTM

**Comment by AnekSahota** [comment]
Nice improvement LGTM

**Comment by bookslifestyle** [comment]
LGTM

**Review by toxicoreos — APPROVED** [review]
Coolio

**Pull request closed without merging**
